packages/bui-core/src/ScrollView/ScrollView.tsx

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**
无

fix: ScrollView部分埋点工具无法区分滑动和点击事件

---

packages/bui-core/src/Tag/Tag.less
packages/bui-core/src/Tag/TagGroup.less
packages/bui-core/src/Tag/__tests__/__snapshots__/Tag.snapshot.test.tsx.snap
packages/bui-core/src/Tag/index.md

优化Tag组合模式样式，改进演示代码
**这个变动的性质是？**
**附加信息（可选）**
完成issue: Closes #4

优化Tag组合模式样式

---

packages/bui-core/src/Modal/Modal.miniapp.tsx
packages/bui-core/src/Picker/Picker.less
packages/bui-core/src/Picker/Picker.tsx
packages/bui-core/src/Picker/Picker.types.ts
packages/bui-core/src/Picker/PickerPanel.less
packages/bui-core/src/Picker/PickerPanel.tsx
packages/bui-core/src/Picker/__tests__/Picker.snapshot.test.tsx
packages/bui-core/src/Picker/__tests__/Picker.test.tsx
packages/bui-core/src/Picker/__tests__/__snapshots__/Picker.snapshot.test.tsx.snap
packages/bui-core/src/Picker/index.md
packages/bui-core/src/Picker/index.ts
packages/bui-core/src/Picker/utils.ts
packages/bui-core/src/index.ts
packages/bui-styles/theme/default-dark.less
packages/bui-styles/theme/default-light.less
packages/bui-styles/theme/dm-dark.less
packages/bui-utils/src/hooks/__tests__/useTouch.test.ts
packages/bui-utils/src/hooks/index.ts
packages/bui-utils/src/hooks/useTouch.ts
packages/bui-utils/src/index.ts

添加Picker选择器组件
**这个变动的性质是？**
**附加信息（可选）**
额外修复Modal组件在小程序环境中disableScrollLock不生效导致的滚动穿透的问题，涉及依赖Modal的组件（ActionSheet、Drawer、Picker），默认不允许滚动穿透。

Add Picker Component

---

packages/bui-styles/index.less

简要描述所做更改
为小红书小程序根组件注入样式变量
**这个变动的性质是？**
**附加信息（可选）**

feat: bui-styles add style variables for xhs-page

---

esbuild.base.ts

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**

fix: 修复按需引入失效

---

esbuild.base.ts

简要描述所做更改
**这个变动的性质是？**
- [X ] 日常 bug 修复
**附加信息（可选）**

feat: 修复dist构建产物异常修复dist构建产物异常

---

packages/bui-core/src/Tabs/Tabs.less
packages/bui-core/src/Tabs/index.md

解决issue：Closes #27 
**这个变动的性质是？**
**附加信息（可选）**

feat: 添加tabline宽高css变量，便于修改

---

.dumi/loading.tsx
package.json
packages/bui-core/src/Calendar/Calendar.tsx
packages/bui-core/src/Calendar/Calendar.types.ts
packages/bui-core/src/Calendar/__tests__/Calendar.test.tsx
packages/bui-core/src/Calendar/index.md
packages/bui-core/src/Countdown/Countdown.tsx
packages/bui-core/src/Radio/Radio.tsx
packages/bui-core/src/Radio/RadioButtonIcon.tsx
packages/bui-core/src/ScrollView/__test__/ScrollView.test.tsx
packages/bui-core/src/Transition/__test__/Transition.test.tsx

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**

优化骨架屏，优化单测脚本报错，修复倒计时组件bug，拓展日期组件快捷切换年份功能

---

.husky/pre-commit
package.json
scripts/check-account/check-credentials.js

git account pre-check, git accounts that do not meet the specifications are not allowed to submit code
**这个变动的性质是？**
**附加信息（可选）**

git account pre-check

---

packages/bui-core/src/Popover/Popover.less
packages/bui-core/src/Popover/Popover.tsx
packages/bui-core/src/Popover/Popover.types.ts
packages/bui-core/src/Popover/index.en-US.md
packages/bui-core/src/Popover/index.zh-CN.md
packages/bui-core/src/Tooltip/Tooltip.less
packages/bui-core/src/Tooltip/Tooltip.tsx
packages/bui-core/src/Tooltip/Tooltip.types.ts
packages/bui-core/src/Tooltip/index.en-US.md
packages/bui-core/src/Tooltip/index.zh-CN.md
packages/bui-utils/src/directionLocationUtil.ts

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**

Tooltip和Popover组件优化

---

packages/bui-core/src/Button/index.en-US.md
packages/bui-core/src/Button/index.zh-CN.md
packages/bui-core/src/Drawer/index.zh-CN.md
packages/bui-core/src/Picker/index.en-US.md
packages/bui-core/src/Picker/index.zh-CN.md
packages/bui-core/src/Popover/Popover.less
packages/bui-core/src/Popover/Popover.tsx
packages/bui-core/src/Popover/__tests__/Popover.test.tsx
packages/bui-core/src/Popover/index.en-US.md
packages/bui-core/src/Popover/index.zh-CN.md
packages/bui-core/src/Portal/Portal.types.ts
packages/bui-core/src/Portal/index.zh-CN.md
packages/bui-core/src/Tooltip/Tooltip.tsx
packages/bui-core/src/Tooltip/__tests__/Tooltip.test.tsx
packages/bui-core/src/Tooltip/index.en-US.md
packages/bui-core/src/Tooltip/index.zh-CN.md
packages/bui-core/src/locales/__tests__/useLocaleText.test.ts
packages/bui-utils/src/directionLocationUtil.ts

1. anywhere click hide tooltip or popover
2. optimize some components docs
3. fix useLocaleText unit test error
**这个变动的性质是？**
**附加信息（可选）**

feat: anywhere click hide tooltip or popover

---

packages/bui-core/src/Button/Button.less
packages/bui-core/src/Button/index.en-US.md
packages/bui-core/src/Button/index.zh-CN.md
packages/bui-core/src/Checkbox/Checkbox.less
packages/bui-core/src/Checkbox/CheckboxGroup.tsx
packages/bui-core/src/Popover/Popover.less
packages/bui-core/src/Popover/index.en-US.md
packages/bui-core/src/Popover/index.zh-CN.md
packages/bui-core/src/Rating/Rating.less
packages/bui-core/src/Select/Select.less
packages/bui-core/src/Select/index.en-US.md
packages/bui-core/src/Select/index.zh-CN.md
packages/bui-core/src/Swiper/index.zh-CN.md
packages/bui-core/src/Tabs/Tab.less
packages/bui-core/src/Tabs/Tabs.less
packages/bui-core/src/Tabs/index.en-US.md
packages/bui-core/src/Tabs/index.zh-CN.md
packages/bui-core/src/Tag/Tag.less
packages/bui-core/src/Tag/index.en-US.md
packages/bui-core/src/Tag/index.zh-CN.md

Fix some component style issues and optimize component documentation
**这个变动的性质是？**
**附加信息（可选）**

Fix some component style issues and optimize component documentation

---

packages/bui-core/src/Badge/__tests__/__snapshots__/Badge.snapshot.test.tsx.snap
packages/bui-core/src/Badge/index.zh-CN.md
packages/bui-core/src/Input/Input.less
packages/bui-core/src/Popover/Popover.less
packages/bui-core/src/Popover/index.en-US.md
packages/bui-core/src/Popover/index.zh-CN.md
packages/bui-core/src/Tabs/TabPanel.tsx
packages/bui-core/src/Tabs/Tabs.tsx
packages/bui-core/src/Tabs/__tests__/Tabs.test.tsx
packages/bui-core/src/Tabs/__tests__/__snapshots__/Tabs.snapshot.test.tsx.snap
packages/bui-core/src/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/bui-core/src/Tabs/index.zh-CN.md
packages/bui-core/src/Toast/index.en-US.md
packages/bui-core/src/Toast/index.zh-CN.md
packages/bui-utils/src/directionLocationUtil.ts

1. Using an invalid value should not select the first Tab by default
2. Optimize some component documents
3. Remove the default behavior of Input super long ellipsis
**这个变动的性质是？**
**附加信息（可选）**

Using an invalid value should not select the first Tab by default

---

packages/bui-core/src/Calendar/Calendar.tsx
packages/bui-core/src/Calendar/Calendar.types.ts
packages/bui-core/src/Calendar/__tests__/Calendar.test.tsx
packages/bui-core/src/Calendar/index.en-US.md
packages/bui-core/src/Calendar/index.zh-CN.md

remove Calendar year picker
**这个变动的性质是？**
**附加信息（可选）**

remove Calendar year picker

---

packages/bui-core/src/Calendar/Calendar.tsx
packages/bui-core/src/Calendar/Calendar.types.ts
packages/bui-core/src/Calendar/__tests__/Calendar.test.tsx
packages/bui-core/src/Calendar/index.en-US.md
packages/bui-core/src/Calendar/index.zh-CN.md

remove Calendar year picker
**这个变动的性质是？**
**附加信息（可选）**

fix: remove Calendar year picker

---

packages/bui-core/src/Input/Input.tsx
packages/bui-core/src/Input/Input.types.ts
packages/bui-core/src/Input/index.en-US.md
packages/bui-core/src/Input/index.zh-CN.md
packages/bui-core/src/Picker/Picker.tsx
packages/bui-core/src/Picker/Picker.types.ts
packages/bui-core/src/Picker/PickerPanel.tsx
packages/bui-core/src/Picker/index.en-US.md
packages/bui-core/src/Picker/index.zh-CN.md
packages/bui-core/src/Picker/utils.ts

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**

修复Input、Picker ts类型定义错误

---

packages/bui-core/src/DatePicker/DatePicker.tsx
packages/bui-core/src/DatePicker/DatePicker.types.ts
packages/bui-core/src/DatePicker/__tests__/DatePicker.test.tsx
packages/bui-core/src/DatePicker/constants.ts
packages/bui-core/src/DatePicker/index.ts
packages/bui-core/src/SwipeAction/SwipeAction.tsx
packages/bui-core/src/SwipeAction/SwipeAction.types.ts
packages/bui-core/src/SwipeAction/__tests__/SwipeAction.test.tsx
packages/bui-core/src/SwipeAction/constants.ts
packages/bui-core/src/SwipeAction/index.ts

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**

fix: enum not found in DatePicker and SwipeAction components

---

.github/workflows/create-release-draft-and-publish.yml
.github/workflows/deploy.yml
package.json
scripts/handle-docs.sh

Support alpha version release
**这个变动的性质是？**
**附加信息（可选）**

Support alpha version release

---

packages/bui-core/src/Swiper/Swiper.tsx

简要描述所做更改
**这个变动的性质是？**
**附加信息（可选）**

fix: Fix the Swiper bug，dynamically modify AutoPlay to cause dom redrawing in a loop

---

packages/bui-core/src/Fade/Fade.miniapp.tsx
packages/bui-core/src/Fade/index.less
packages/bui-core/src/Slide/Slide.miniapp.tsx

修复Fade组件out动画结束遮挡其他组件影响点击事件问题
优化Fade、Slide的isMounted、isFirstMount的判断逻辑
**这个变动的性质是？**
**附加信息（可选）**

fix: optimize state initialization for fade and slide components
